### ISSUE TITLE
In Time Warp, how to choose parameter W?

### ISSUE THREAD

**Issue by DevKiHyun** [zcaceres/spec_augment#1]
Hi, thank you for good github. I wonder that how to choose parameter W? Just random? I wonder what the range is if this is selected randomly.

**Comment by zcaceres** [comment]
Hi there! I'm still working on the time warp function. If you have an implementation I'd love to include it here :-)

The paper includes a parameter schedule that shows W as 80 for their training set. I believe it's somewhat arbitrary except that it needs to be smaller than the full length of the audio and big enough to create a nice range of possible shift values.

**Comment by DevKiHyun** [comment]
@zcaceres Thank you!
