### ISSUE TITLE
Change in nb_SparseImageWarp.py to adapt newer version of pytorch

### ISSUE THREAD

**Issue by lukewys** [zcaceres/spec_augment#11]
Hi, I found some code in nb_SparseImageWarp.py need changes in order to work in Pytorch 1.4.0:

In line 115:
X, LU = torch.gesv(rhs, lhs) ->
X, LU = torch.solve(rhs, lhs)
(torch.gesv has been deprecated)

In line 160: 
return 0.5 * torch.square(r) * torch.log(torch.max(r, EPSILON)) ->
return 0.5 * r.pow(2) * torch.log(torch.max(r, EPSILON))

There are also warnings:
nb_SparseImageWarp.py:316: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  alpha = torch.tensor(queries - floor, dtype=grid_type)

But I think it will still be working properly.

Hope that might help.

**Comment by lukewys** [comment]
line 316: change to:
alpha = queries - floor

Will solve the warning

**Comment by shangeth** [comment]
```
    213         return r
    214     elif order == 2:
--> 215         return 0.5 * r.pow(2) * torch.log(torch.max(r, EPSILON))
    216     elif order == 4:
    217         return 0.5 * torch.square(r) * torch.log(torch.max(r, EPSILON))

RuntimeError: iter.device(arg).is_cuda() INTERNAL ASSERT FAILED at "/pytorch/aten/src/ATen/native/cuda/Loops.cuh":61, please report a bug to PyTorch. 
```

Changing return 0.5 * torch.square(r) * torch.log(torch.max(r, EPSILON)) -> return 0.5 * r.pow(2) * torch.log(torch.max(r, EPSILON))  still gives error.

**Comment by zcaceres** [comment]
Please put up a PR and I'm happy to review and merge.
