### ISSUE TITLE
fatal error: sox.h: No such file or directory 

### ISSUE THREAD

**Issue by Aditya3107** [zcaceres/spec_augment#13]
Hi, 

I am trying to run your code  install.sh file in conda environment and getting an error 

`cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/mds-student/Documents/SpecAUGMENT/spec_augment-2647a201138079f6486977a25a937133e3c5e825/torchaudio/torchaudio/csrc/sox_effects.h:,
                 from /home/mds-student/Documents/SpecAUGMENT/spec_augment-2647a201138079f6486977a25a937133e3c5e825/torchaudio/torchaudio/csrc/register.cpp:4:
/home/mds-student/Documents/SpecAUGMENT/spec_augment-2647a201138079f6486977a25a937133e3c5e825/torchaudio/torchaudio/csrc/sox_utils.h:4:10: fatal error: sox.h: No such file or directory
    4 | #include <sox.h>
      |          ^~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1
./install.sh: line 7: jupyter: command not found`

Can you suggest me some solution ?

**Comment by zcaceres** [comment]
By the looks of it, you need to install Jupyter
