### ISSUE TITLE
Convert speech to text?

### ISSUE THREAD

**Issue by youssefavx** [zcaceres/spec_augment#14]
Have I misunderstood that SpecAugment could be used to convert speech to text? It seems from your Medium article that it is simply something that enhances the process of one training a model rather than converts speech to text. Am I correct on this? I'm searching for the nearest model available online (for free) with the lowest WER which I can simply give audio and get text back with probabilities. Would appreciate any tips on that!

**Comment by zcaceres** [comment]
It does not support this. It is a data augmentation technique for learning from audio data. That's all! Check out ESPNet.
