### ISSUE TITLE
It seems that there are two masking colors, Right?

### ISSUE THREAD

**Issue by bemoregt** [zcaceres/spec_augment#2]
Hi, @qcai2002 @zcaceres 

It seems that there are two masking colors, Green and Yellow in pseudo-colors. right ?
Think of  0~255 pixel levels, Green is 128 level, and Yellow is 255 level?

Thanks.

**Comment by jennycai2** [comment]
Thank you for your questions, Gromit. Which lines of code are you referring
to? By pseudo-colors, do you mean a value being decided randomly, i.e.
choosing
for green, G = 255
for yellow, R = 128, G=128

Thanks for the discussion in advance.

Jenny

**Comment by zcaceres** [comment]
Hi @bemoregt 

The color differences reflect the use of the mean value OR zero to mask the frequency or time bands. The Spec Augment paper uses the mean value of the spectrograms to mask. But zero also seems like a reasonable value so you can optionally use that too. The matplotlib visualization shows the zero and mean values as different colors.
