### ISSUE TITLE
Problem about the wrong result

### ISSUE THREAD

**Issue by lijuan123** [zcaceres/spec_augment#5]
Hi, thanks for your perfect job. However, when I  test the function of time_warp with the input following:
![image](https://user-images.githubusercontent.com/20534234/57208233-571a4e80-7005-11e9-9adf-79727dca69b4.png)
I got the result which seems wrong
![image](https://user-images.githubusercontent.com/20534234/57208250-71542c80-7005-11e9-86c5-aa97c548c950.png)
I use the mfsc feature and the the image size is 400*128dim，W and other parameters are set default. I have no idea about the reason of wrong result. Would you like to give me some suggestions? Thank you very much

**Comment by zcaceres** [comment]
I believe the problem is with the default 'W' parameter. How far you can shift (without having to worry about padding/boundaries on the edges of the spectrogram) depends on the dimensions of your spectrogram.

Try a smaller W value and see how it goes!
