### ISSUE TITLE
How to include your code in our library

### ISSUE THREAD

**Issue by bobchennan** [zcaceres/spec_augment#7]
In my initial experiments I got some promising results with our [ASR library](https://github.com/espnet/espnet). Can I include a modified py version in our library? How can I reference your work? I didn't see any license anywhere.

**Comment by zcaceres** [comment]
Hi @bobchennan the repo is now MIT Licensed, feel free to use. Of course a friendly link back or little credit in the ReadMe would be appreciated if you use it.
