### ISSUE TITLE
Is it able to warp color image(3 channel) ?

### ISSUE THREAD

**Issue by wtjiang98** [zcaceres/spec_augment#9]
It seems that the shape of input image is (b, h, w), while the same function in TensorFlow can deal with color image. Is the library able to warp color image(3 channel) by simply add a dismension on code?

**Comment by zcaceres** [comment]
Hi @taogelose , sorry but I doubt that it will work just by adding a channel dimension. You are more than welcome to check out the code and make a PR or see if the methods used can be extended for the channel dimension.

**Comment by wtjiang98** [comment]
Thank you for the advise, I have implement it. I will make a PR soon.
